version: '3.7'
services:
  nginx:
    image: ghcr.io/automattic/vip-container-images/nginx:1.23.3
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ..:/usr/share/nginx/html
    depends_on:
      - php-fpm
  php-fpm:
    image: php:7.4-fpm
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      APP_ENV: dev
    command: "php-fpm"