version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/app
    depends_on:
      - php-fpm
  php-fpm:
    image: php:7.4-fpm
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      APP_ENV: dev
    command: "php-fpm"